/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseAdapter;

/**
 *
 * @author ciara
 */
public class adminHome extends javax.swing.JFrame {
private static adminHome obj=null;
    /**
     * Creates new form adminAdd
     */
    public adminHome() {
        initComponents();
    }


    public static adminHome getObj(){
        if(obj==null){
           obj= new adminHome();
        }return obj;
    }
    /**
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pDashboard = new javax.swing.JPanel();
        iconSilau = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        lNama = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bHome = new javax.swing.JLabel();
        bSignout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bSong = new javax.swing.JLabel();
        bAlbum = new javax.swing.JLabel();
        bArtist = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pSong2 = new javax.swing.JPanel();
        SongIcon2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jmlSongs = new javax.swing.JLabel();
        pArtist = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ArtistIcon1 = new javax.swing.JLabel();
        jmlArtist = new javax.swing.JLabel();
        pAlbum = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        WordIcon1 = new javax.swing.JLabel();
        jmlAlbum = new javax.swing.JLabel();
        bAddSong = new javax.swing.JLabel();
        bViewS = new javax.swing.JLabel();
        bAddAlbum = new javax.swing.JLabel();
        bViewAlbum = new javax.swing.JLabel();
        bAddArtist = new javax.swing.JLabel();
        bViewArt = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1341, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(249, 117, 117));
        jPanel1.setPreferredSize(new java.awt.Dimension(1921, 1100));
        jPanel1.setLayout(null);

        pDashboard.setBackground(new java.awt.Color(22, 56, 80));

        iconSilau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icon.png"))); // NOI18N

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/user.png"))); // NOI18N

        lNama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lNama.setForeground(new java.awt.Color(255, 255, 255));
        lNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNama.setText("admin");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        bHome.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        bHome.setForeground(new java.awt.Color(255, 255, 255));
        bHome.setText("Home");

        bSignout.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bSignout.setForeground(new java.awt.Color(255, 255, 255));
        bSignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/signoutIcon.png"))); // NOI18N
        bSignout.setText("Sign Out");
        bSignout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSignout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSignoutMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 143, 215));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HI, ADMIN!");

        bSong.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bSong.setForeground(new java.awt.Color(255, 255, 255));
        bSong.setText("Song");
        bSong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSongMouseClicked(evt);
            }
        });

        bAlbum.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bAlbum.setForeground(new java.awt.Color(255, 255, 255));
        bAlbum.setText("Album");
        bAlbum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAlbumMouseClicked(evt);
            }
        });

        bArtist.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bArtist.setForeground(new java.awt.Color(255, 255, 255));
        bArtist.setText("Artist");
        bArtist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bArtist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bArtistMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pDashboardLayout = new javax.swing.GroupLayout(pDashboard);
        pDashboard.setLayout(pDashboardLayout);
        pDashboardLayout.setHorizontalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                .addGap(0, 56, Short.MAX_VALUE)
                .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                        .addComponent(iconSilau)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                        .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDashboardLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(userIcon))
                            .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDashboardLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bHome)
                                    .addComponent(bSignout)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bSong)
                                    .addComponent(bArtist)
                                    .addComponent(bAlbum))))
                        .addGap(54, 54, 54))))
        );
        pDashboardLayout.setVerticalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashboardLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(iconSilau)
                .addGap(45, 45, 45)
                .addComponent(userIcon)
                .addGap(18, 18, 18)
                .addComponent(lNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bArtist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAlbum)
                .addGap(162, 162, 162)
                .addComponent(bSignout)
                .addContainerGap(419, Short.MAX_VALUE))
        );

        jPanel1.add(pDashboard);
        pDashboard.setBounds(0, 0, 370, 1100);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        pSong2.setBackground(new java.awt.Color(254, 218, 153));

        SongIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/albumm.png"))); // NOI18N
        SongIcon2.setText("jLabel7");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel3.setText("Song");

        jmlSongs.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jmlSongs.setText("jumlah");

        javax.swing.GroupLayout pSong2Layout = new javax.swing.GroupLayout(pSong2);
        pSong2.setLayout(pSong2Layout);
        pSong2Layout.setHorizontalGroup(
            pSong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSong2Layout.createSequentialGroup()
                .addGroup(pSong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSong2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(SongIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pSong2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jmlSongs)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSong2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(79, 79, 79))
        );
        pSong2Layout.setVerticalGroup(
            pSong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSong2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(SongIcon2)
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jmlSongs)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.add(pSong2);
        pSong2.setBounds(90, 170, 230, 280);

        pArtist.setBackground(new java.awt.Color(254, 218, 153));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel4.setText("Artist");

        ArtistIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/singer.png"))); // NOI18N
        ArtistIcon1.setText("jLabel7");

        jmlArtist.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jmlArtist.setText("jumlah");

        javax.swing.GroupLayout pArtistLayout = new javax.swing.GroupLayout(pArtist);
        pArtist.setLayout(pArtistLayout);
        pArtistLayout.setHorizontalGroup(
            pArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pArtistLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pArtistLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(ArtistIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pArtistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jmlArtist)
                .addGap(88, 88, 88))
        );
        pArtistLayout.setVerticalGroup(
            pArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pArtistLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(ArtistIcon1)
                .addGap(2, 2, 2)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmlArtist)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(pArtist);
        pArtist.setBounds(350, 170, 230, 280);

        pAlbum.setBackground(new java.awt.Color(254, 218, 153));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel9.setText("Album");

        WordIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/word.png"))); // NOI18N
        WordIcon1.setText("jLabel7");

        jmlAlbum.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jmlAlbum.setText("jumlah");

        javax.swing.GroupLayout pAlbumLayout = new javax.swing.GroupLayout(pAlbum);
        pAlbum.setLayout(pAlbumLayout);
        pAlbumLayout.setHorizontalGroup(
            pAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlbumLayout.createSequentialGroup()
                .addGroup(pAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAlbumLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel9))
                    .addGroup(pAlbumLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(WordIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pAlbumLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jmlAlbum)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        pAlbumLayout.setVerticalGroup(
            pAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlbumLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(WordIcon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmlAlbum)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.add(pAlbum);
        pAlbum.setBounds(610, 170, 230, 280);

        bAddSong.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bAddSong.setText("Add");
        bAddSong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAddSong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAddSongMouseClicked(evt);
            }
        });
        jPanel2.add(bAddSong);
        bAddSong.setBounds(100, 460, 60, 29);

        bViewS.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bViewS.setText("View All");
        bViewS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bViewS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bViewSMouseClicked(evt);
            }
        });
        jPanel2.add(bViewS);
        bViewS.setBounds(220, 460, 90, 29);

        bAddAlbum.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bAddAlbum.setText("Add");
        bAddAlbum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAddAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAddAlbumMouseClicked(evt);
            }
        });
        jPanel2.add(bAddAlbum);
        bAddAlbum.setBounds(620, 460, 60, 29);

        bViewAlbum.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bViewAlbum.setText("View All");
        bViewAlbum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bViewAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bViewAlbumMouseClicked(evt);
            }
        });
        jPanel2.add(bViewAlbum);
        bViewAlbum.setBounds(740, 460, 90, 29);

        bAddArtist.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bAddArtist.setText("Add");
        bAddArtist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAddArtist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAddArtistMouseClicked(evt);
            }
        });
        jPanel2.add(bAddArtist);
        bAddArtist.setBounds(360, 460, 60, 29);

        bViewArt.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bViewArt.setText("View All");
        bViewArt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bViewArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bViewArtMouseClicked(evt);
            }
        });
        jPanel2.add(bViewArt);
        bViewArt.setBounds(480, 460, 90, 29);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(370, 0, 980, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1341, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bAddSongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAddSongMouseClicked
        //adminAddSong.getObj().setVisible(true);
    }//GEN-LAST:event_bAddSongMouseClicked

    private void bViewSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bViewSMouseClicked
     
       // adminVSong.getObj().setVisible(true);
        
    }//GEN-LAST:event_bViewSMouseClicked

    private void bAddArtistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAddArtistMouseClicked
        //adminAddArtist.getObj().setVisible(true);
    }//GEN-LAST:event_bAddArtistMouseClicked

    private void bViewArtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bViewArtMouseClicked
       
        //adminVAr.getObj().setVisible(true);
    }//GEN-LAST:event_bViewArtMouseClicked

    private void bAddAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAddAlbumMouseClicked
        //adminAddAlbum.getObj().setVisible(true);
    }//GEN-LAST:event_bAddAlbumMouseClicked

    private void bViewAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bViewAlbumMouseClicked
        
    }//GEN-LAST:event_bViewAlbumMouseClicked

    private void bAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAlbumMouseClicked
       
        adminVAl.getObj().setVisible(true);;
    }//GEN-LAST:event_bAlbumMouseClicked

    private void bArtistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bArtistMouseClicked
        
        adminVAr.getObj().setVisible(true);
    }//GEN-LAST:event_bArtistMouseClicked

    private void bSongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSongMouseClicked
        
        adminVSong.getObj().setVisible(true);
        
    }//GEN-LAST:event_bSongMouseClicked

    private void bSignoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSignoutMouseClicked
        adminHome.getObj().dispose();
    }//GEN-LAST:event_bSignoutMouseClicked

    public void addbAddArtist(MouseAdapter adapter){
        bAddArtist.addMouseListener(adapter);
    }
    public void addbAddSong(MouseAdapter adapter){
        bAddSong.addMouseListener(adapter);
    }
    public void addbAddAlbum(MouseAdapter adapter){
        bAddAlbum.addMouseListener(adapter);
    }
    public void addbViewAlbum(MouseAdapter adapter){
        bViewAlbum.addMouseListener(adapter);
    }
    public void addbViewArt(MouseAdapter adapter){
        bViewArt.addMouseListener(adapter);
    }
    public void addbViewS(MouseAdapter adapter){
        bViewS.addMouseListener(adapter);
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArtistIcon1;
    private javax.swing.JLabel SongIcon2;
    private javax.swing.JLabel WordIcon1;
    private javax.swing.JLabel bAddAlbum;
    private javax.swing.JLabel bAddArtist;
    private javax.swing.JLabel bAddSong;
    private javax.swing.JLabel bAlbum;
    private javax.swing.JLabel bArtist;
    private javax.swing.JLabel bHome;
    private javax.swing.JLabel bSignout;
    private javax.swing.JLabel bSong;
    private javax.swing.JLabel bViewAlbum;
    private javax.swing.JLabel bViewArt;
    private javax.swing.JLabel bViewS;
    private javax.swing.JLabel iconSilau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jmlAlbum;
    private javax.swing.JLabel jmlArtist;
    private javax.swing.JLabel jmlSongs;
    private javax.swing.JLabel lNama;
    private javax.swing.JPanel pAlbum;
    private javax.swing.JPanel pArtist;
    private javax.swing.JPanel pDashboard;
    private javax.swing.JPanel pSong2;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
