/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.KeyEvent;
import javax.swing.JTable;

/**
 *
 * @author ciara
 */
public class adminVAr extends javax.swing.JFrame {
private static adminVAr obj=null;
    public adminVAr() {
        initComponents();
    }
    
    public static adminVAr getObj(){
        if(obj==null){
           obj= new adminVAr();
        }return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pDashboard = new javax.swing.JPanel();
        iconSilau = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        lNama = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bHome = new javax.swing.JLabel();
        bSignout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bSong = new javax.swing.JLabel();
        bAlbum = new javax.swing.JLabel();
        bHome1 = new javax.swing.JLabel();
        bViewArt = new javax.swing.JPanel();
        pSong2 = new javax.swing.JPanel();
        SongIcon2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jmlSongs = new javax.swing.JLabel();
        pArtist = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ArtistIcon1 = new javax.swing.JLabel();
        jmlArtist = new javax.swing.JLabel();
        pAlbum = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        WordIcon1 = new javax.swing.JLabel();
        jmlAlbum = new javax.swing.JLabel();
        bAddSong = new javax.swing.JLabel();
        bViewS = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bAddArtist = new javax.swing.JLabel();
        bAddAlbum = new javax.swing.JLabel();
        bViewAlbum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblArtist = new javax.swing.JTable();
        bDelArtist = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bEditArtist = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelSearch = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        searchIcon = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1347, 711));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(249, 117, 117));
        jPanel1.setPreferredSize(new java.awt.Dimension(1921, 1100));
        jPanel1.setLayout(null);

        pDashboard.setBackground(new java.awt.Color(22, 56, 80));

        iconSilau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icon.png"))); // NOI18N

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/user.png"))); // NOI18N

        lNama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lNama.setForeground(new java.awt.Color(255, 255, 255));
        lNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNama.setText("admin");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        bHome.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bHome.setForeground(new java.awt.Color(255, 255, 255));
        bHome.setText("Home");
        bHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bHomeMouseClicked(evt);
            }
        });

        bSignout.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bSignout.setForeground(new java.awt.Color(255, 255, 255));
        bSignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/signoutIcon.png"))); // NOI18N
        bSignout.setText("Sign Out");
        bSignout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSignoutMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 143, 215));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HI, ADMIN!");

        bSong.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bSong.setForeground(new java.awt.Color(255, 255, 255));
        bSong.setText("Song");
        bSong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSongMouseClicked(evt);
            }
        });

        bAlbum.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bAlbum.setForeground(new java.awt.Color(255, 255, 255));
        bAlbum.setText("Album");
        bAlbum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAlbumMouseClicked(evt);
            }
        });

        bHome1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        bHome1.setForeground(new java.awt.Color(255, 255, 255));
        bHome1.setText("Artist");

        javax.swing.GroupLayout pDashboardLayout = new javax.swing.GroupLayout(pDashboard);
        pDashboard.setLayout(pDashboardLayout);
        pDashboardLayout.setHorizontalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                .addGap(0, 56, Short.MAX_VALUE)
                .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                        .addComponent(iconSilau)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                        .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDashboardLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(userIcon))
                            .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDashboardLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bHome)
                                    .addComponent(bSignout)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bSong)
                                    .addComponent(bHome1)
                                    .addComponent(bAlbum))))
                        .addGap(54, 54, 54))))
        );
        pDashboardLayout.setVerticalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashboardLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(iconSilau)
                .addGap(45, 45, 45)
                .addComponent(userIcon)
                .addGap(18, 18, 18)
                .addComponent(lNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bHome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAlbum)
                .addGap(162, 162, 162)
                .addComponent(bSignout)
                .addContainerGap(419, Short.MAX_VALUE))
        );

        jPanel1.add(pDashboard);
        pDashboard.setBounds(0, 0, 370, 1100);

        bViewArt.setBackground(new java.awt.Color(255, 255, 255));
        bViewArt.setLayout(null);

        pSong2.setBackground(new java.awt.Color(254, 218, 153));

        SongIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/albumm.png"))); // NOI18N
        SongIcon2.setText("jLabel7");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel3.setText("Song");

        jmlSongs.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jmlSongs.setText("jumlah");

        javax.swing.GroupLayout pSong2Layout = new javax.swing.GroupLayout(pSong2);
        pSong2.setLayout(pSong2Layout);
        pSong2Layout.setHorizontalGroup(
            pSong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSong2Layout.createSequentialGroup()
                .addGroup(pSong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSong2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(SongIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pSong2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jmlSongs)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSong2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(79, 79, 79))
        );
        pSong2Layout.setVerticalGroup(
            pSong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSong2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(SongIcon2)
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jmlSongs)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        bViewArt.add(pSong2);
        pSong2.setBounds(40, 20, 230, 280);

        pArtist.setBackground(new java.awt.Color(254, 218, 153));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel4.setText("Artist");

        ArtistIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/singer.png"))); // NOI18N
        ArtistIcon1.setText("jLabel7");

        jmlArtist.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jmlArtist.setText("jumlah");

        javax.swing.GroupLayout pArtistLayout = new javax.swing.GroupLayout(pArtist);
        pArtist.setLayout(pArtistLayout);
        pArtistLayout.setHorizontalGroup(
            pArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pArtistLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pArtistLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(ArtistIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pArtistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jmlArtist)
                .addGap(88, 88, 88))
        );
        pArtistLayout.setVerticalGroup(
            pArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pArtistLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(ArtistIcon1)
                .addGap(2, 2, 2)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmlArtist)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bViewArt.add(pArtist);
        pArtist.setBounds(300, 20, 230, 280);

        pAlbum.setBackground(new java.awt.Color(254, 218, 153));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel9.setText("Album");

        WordIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/word.png"))); // NOI18N
        WordIcon1.setText("jLabel7");

        jmlAlbum.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jmlAlbum.setText("jumlah");

        javax.swing.GroupLayout pAlbumLayout = new javax.swing.GroupLayout(pAlbum);
        pAlbum.setLayout(pAlbumLayout);
        pAlbumLayout.setHorizontalGroup(
            pAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlbumLayout.createSequentialGroup()
                .addGroup(pAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAlbumLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel9))
                    .addGroup(pAlbumLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(WordIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pAlbumLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jmlAlbum)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        pAlbumLayout.setVerticalGroup(
            pAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlbumLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(WordIcon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmlAlbum)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        bViewArt.add(pAlbum);
        pAlbum.setBounds(550, 20, 230, 280);

        bAddSong.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bAddSong.setText("Add");
        bAddSong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAddSong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAddSongMouseClicked(evt);
            }
        });
        bViewArt.add(bAddSong);
        bAddSong.setBounds(50, 310, 60, 29);

        bViewS.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bViewS.setText("View All");
        bViewS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bViewS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bViewSMouseClicked(evt);
            }
        });
        bViewArt.add(bViewS);
        bViewS.setBounds(170, 310, 90, 29);

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel14.setText("View All");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bViewArt.add(jLabel14);
        jLabel14.setBounds(430, 310, 90, 29);

        bAddArtist.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bAddArtist.setText("Add");
        bAddArtist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAddArtist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAddArtistMouseClicked(evt);
            }
        });
        bViewArt.add(bAddArtist);
        bAddArtist.setBounds(310, 310, 60, 29);

        bAddAlbum.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bAddAlbum.setText("Add");
        bAddAlbum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAddAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAddAlbumMouseClicked(evt);
            }
        });
        bViewArt.add(bAddAlbum);
        bAddAlbum.setBounds(560, 310, 60, 29);

        bViewAlbum.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bViewAlbum.setText("View All");
        bViewAlbum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bViewAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bViewAlbumMouseClicked(evt);
            }
        });
        bViewArt.add(bViewAlbum);
        bViewAlbum.setBounds(680, 310, 90, 29);

        jScrollPane1.setBorder(null);

        jScrollPane2.setBorder(null);

        tblArtist.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tblArtist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblArtist);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 339, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(jPanel4);

        bViewArt.add(jScrollPane1);
        jScrollPane1.setBounds(40, 430, 750, 250);

        bDelArtist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bDelArtist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDelArtistMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel5.setText("Delete");

        javax.swing.GroupLayout bDelArtistLayout = new javax.swing.GroupLayout(bDelArtist);
        bDelArtist.setLayout(bDelArtistLayout);
        bDelArtistLayout.setHorizontalGroup(
            bDelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bDelArtistLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        bDelArtistLayout.setVerticalGroup(
            bDelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bDelArtistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        bViewArt.add(bDelArtist);
        bDelArtist.setBounds(800, 170, 100, 50);

        bEditArtist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEditArtist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEditArtistMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("Edit");

        javax.swing.GroupLayout bEditArtistLayout = new javax.swing.GroupLayout(bEditArtist);
        bEditArtist.setLayout(bEditArtistLayout);
        bEditArtistLayout.setHorizontalGroup(
            bEditArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bEditArtistLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        bEditArtistLayout.setVerticalGroup(
            bEditArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bEditArtistLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bViewArt.add(bEditArtist);
        bEditArtist.setBounds(800, 250, 100, 50);

        panelSearch.setBackground(new java.awt.Color(255, 255, 255));
        panelSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 173, 179)));

        search.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        search.setBorder(null);
        search.setMargin(new java.awt.Insets(2, 4, 2, 2));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });

        searchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/search.png"))); // NOI18N

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(searchIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchIcon)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bViewArt.add(panelSearch);
        panelSearch.setBounds(40, 360, 750, 60);

        jPanel1.add(bViewArt);
        bViewArt.setBounds(370, 0, 980, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bAddSongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAddSongMouseClicked
        adminAddSong.getObj().setVisible(true);
    }//GEN-LAST:event_bAddSongMouseClicked

    private void bAddArtistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAddArtistMouseClicked
        adminAddArtist.getObj().setVisible(true);
    }//GEN-LAST:event_bAddArtistMouseClicked

    private void bViewSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bViewSMouseClicked
        adminVAr.getObj().dispose();
        adminVSong.getObj().setVisible(true);
    }//GEN-LAST:event_bViewSMouseClicked

    private void bAddAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAddAlbumMouseClicked
        adminAddAlbum.getObj().setVisible(true);
    }//GEN-LAST:event_bAddAlbumMouseClicked

    private void bViewAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bViewAlbumMouseClicked
        adminVAr.getObj().dispose();
        adminVAl.getObj().setVisible(true);
    }//GEN-LAST:event_bViewAlbumMouseClicked

    private void bDelArtistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDelArtistMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bDelArtistMouseClicked

    private void bEditArtistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditArtistMouseClicked
        adminEditArtist.getObj().setVisible(true);
    }//GEN-LAST:event_bEditArtistMouseClicked

    private void bSignoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSignoutMouseClicked
        adminVAr.getObj().dispose();
        adminHome.getObj().dispose();
    }//GEN-LAST:event_bSignoutMouseClicked

    private void bHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHomeMouseClicked
        adminVAr.getObj().dispose();
    }//GEN-LAST:event_bHomeMouseClicked

    private void bSongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSongMouseClicked
        adminVAr.getObj().dispose();
        adminVSong.getObj().setVisible(true);
    }//GEN-LAST:event_bSongMouseClicked

    private void bAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAlbumMouseClicked
        adminVAr.getObj().dispose();
        adminVAl.getObj().setVisible(true);
    }//GEN-LAST:event_bAlbumMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

        }
    }//GEN-LAST:event_searchKeyPressed

    public JTable gettblArtist() {
        return tblArtist;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArtistIcon1;
    private javax.swing.JLabel SongIcon2;
    private javax.swing.JLabel WordIcon1;
    private javax.swing.JLabel bAddAlbum;
    private javax.swing.JLabel bAddArtist;
    private javax.swing.JLabel bAddSong;
    private javax.swing.JLabel bAlbum;
    private javax.swing.JPanel bDelArtist;
    private javax.swing.JPanel bEditArtist;
    private javax.swing.JLabel bHome;
    private javax.swing.JLabel bHome1;
    private javax.swing.JLabel bSignout;
    private javax.swing.JLabel bSong;
    private javax.swing.JLabel bViewAlbum;
    private javax.swing.JPanel bViewArt;
    private javax.swing.JLabel bViewS;
    private javax.swing.JLabel iconSilau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jmlAlbum;
    private javax.swing.JLabel jmlArtist;
    private javax.swing.JLabel jmlSongs;
    private javax.swing.JLabel lNama;
    private javax.swing.JPanel pAlbum;
    private javax.swing.JPanel pArtist;
    private javax.swing.JPanel pDashboard;
    private javax.swing.JPanel pSong2;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JTextField search;
    private javax.swing.JLabel searchIcon;
    private javax.swing.JTable tblArtist;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
