/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;

/**
 *
 * @author ciara
 */
public class adminEditAlbum extends javax.swing.JFrame {
private static adminEditAlbum obj=null;
    
    public adminEditAlbum() {
        initComponents();
    }
    public static adminEditAlbum getObj(){
        if(obj==null){
           obj= new adminEditAlbum();
        }return obj;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLoginL = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addIDAlbm = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addJudulAlbm = new javax.swing.JTextField();
        bSubmit = new javax.swing.JPanel();
        arrRight = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        addJudulS2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        addGenre = new javax.swing.JTextField();
        judul2 = new javax.swing.JLabel();
        judul3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        addRilisA = new javax.swing.JFormattedTextField();
        judul4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        addProdAl = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(620, 622));
        setResizable(false);

        pLoginL.setBackground(new java.awt.Color(255, 255, 255));
        pLoginL.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(249, 249, 249));

        addIDAlbm.setEditable(false);
        addIDAlbm.setBackground(new java.awt.Color(249, 249, 249));
        addIDAlbm.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        addIDAlbm.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addIDAlbm, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addIDAlbm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pLoginL.add(jPanel2);
        jPanel2.setBounds(40, 160, 440, 60);

        id.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        id.setText("ID Album");
        pLoginL.add(id);
        id.setBounds(50, 130, 120, 29);

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));

        addJudulAlbm.setBackground(new java.awt.Color(249, 249, 249));
        addJudulAlbm.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        addJudulAlbm.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addJudulAlbm, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addJudulAlbm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pLoginL.add(jPanel1);
        jPanel1.setBounds(40, 250, 440, 60);

        bSubmit.setBackground(new java.awt.Color(254, 182, 53));
        bSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSubmitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bSubmitMouseExited(evt);
            }
        });

        arrRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/arrowright.png"))); // NOI18N

        javax.swing.GroupLayout bSubmitLayout = new javax.swing.GroupLayout(bSubmit);
        bSubmit.setLayout(bSubmitLayout);
        bSubmitLayout.setHorizontalGroup(
            bSubmitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bSubmitLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(arrRight)
                .addGap(23, 23, 23))
        );
        bSubmitLayout.setVerticalGroup(
            bSubmitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bSubmitLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(arrRight)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pLoginL.add(bSubmit);
        bSubmit.setBounds(520, 280, 70, 160);

        judul.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        judul.setText("Genre");
        pLoginL.add(judul);
        judul.setBounds(50, 320, 120, 29);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel1.setText("Update Album");
        pLoginL.add(jLabel1);
        jLabel1.setBounds(150, 50, 310, 50);

        jPanel5.setBackground(new java.awt.Color(249, 249, 249));

        addJudulS2.setBackground(new java.awt.Color(249, 249, 249));
        addJudulS2.setBorder(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addJudulS2, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addJudulS2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pLoginL.add(jPanel5);
        jPanel5.setBounds(40, 250, 440, 60);

        jPanel4.setBackground(new java.awt.Color(249, 249, 249));

        addGenre.setBackground(new java.awt.Color(249, 249, 249));
        addGenre.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        addGenre.setBorder(null);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addGenre, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addGenre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pLoginL.add(jPanel4);
        jPanel4.setBounds(40, 350, 440, 60);

        judul2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        judul2.setText("Name");
        pLoginL.add(judul2);
        judul2.setBounds(50, 220, 120, 29);

        judul3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        judul3.setText("Released Date");
        pLoginL.add(judul3);
        judul3.setBounds(50, 410, 160, 29);

        jPanel6.setBackground(new java.awt.Color(249, 249, 249));

        addRilisA.setBackground(new java.awt.Color(249, 249, 249));
        addRilisA.setBorder(null);
        addRilisA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        addRilisA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addRilisAMouseEntered(evt);
            }
        });
        addRilisA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRilisAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addRilisA, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addRilisA, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pLoginL.add(jPanel6);
        jPanel6.setBounds(40, 440, 440, 60);

        judul4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        judul4.setText("Produced by");
        pLoginL.add(judul4);
        judul4.setBounds(50, 510, 150, 29);

        jPanel7.setBackground(new java.awt.Color(249, 249, 249));

        addProdAl.setBackground(new java.awt.Color(249, 249, 249));
        addProdAl.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        addProdAl.setBorder(null);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addProdAl, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addProdAl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pLoginL.add(jPanel7);
        jPanel7.setBounds(40, 540, 440, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pLoginL, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pLoginL, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSubmitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bSubmitMouseClicked

    private void bSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSubmitMouseEntered
        bSubmit.setBackground(new Color(255, 197, 91));
    }//GEN-LAST:event_bSubmitMouseEntered

    private void bSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSubmitMouseExited
        bSubmit.setBackground(new Color(254, 182, 53));
    }//GEN-LAST:event_bSubmitMouseExited

    private void addRilisAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRilisAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRilisAActionPerformed

    private void addRilisAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRilisAMouseEntered
        addRilisA.setFont(new java.awt.Font("Roboto", 0, 24));
    }//GEN-LAST:event_addRilisAMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addGenre;
    private javax.swing.JTextField addIDAlbm;
    private javax.swing.JTextField addJudulAlbm;
    private javax.swing.JTextField addJudulS2;
    private javax.swing.JTextField addProdAl;
    private javax.swing.JFormattedTextField addRilisA;
    private javax.swing.JLabel arrRight;
    private javax.swing.JPanel bSubmit;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    private javax.swing.JLabel judul4;
    private javax.swing.JPanel pLoginL;
    // End of variables declaration//GEN-END:variables
}
