/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.sql.Date;
import javax.swing.JTable;

/**
 *
 * @author ciara
 */
public class adminAddAlbum extends javax.swing.JFrame {
private static adminAddAlbum obj=null;
    
    public adminAddAlbum() {
        initComponents();
    }
    public static adminAddAlbum getObj(){
        if(obj==null){
           obj= new adminAddAlbum();
        }return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLoginL = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tfIDAlbum = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tfName = new javax.swing.JTextField();
        bSubmit = new javax.swing.JPanel();
        arrRight = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        addJudulS2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        tfGenre = new javax.swing.JTextField();
        judul2 = new javax.swing.JLabel();
        judul3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tfRilis = new javax.swing.JFormattedTextField();
        judul4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        tfProduser = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArtist = new javax.swing.JTable();
        bPenyanyi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setResizable(false);

        pLoginL.setBackground(new java.awt.Color(255, 255, 255));
        pLoginL.setMaximumSize(new java.awt.Dimension(60, 657));
        pLoginL.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(249, 249, 249));

        tfIDAlbum.setBackground(new java.awt.Color(249, 249, 249));
        tfIDAlbum.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        tfIDAlbum.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfIDAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfIDAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pLoginL.add(jPanel2);
        jPanel2.setBounds(40, 160, 440, 60);

        id.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        id.setText("ID Album");
        pLoginL.add(id);
        id.setBounds(50, 130, 120, 29);

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));

        tfName.setBackground(new java.awt.Color(249, 249, 249));
        tfName.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        tfName.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pLoginL.add(jPanel1);
        jPanel1.setBounds(40, 250, 440, 60);

        bSubmit.setBackground(new java.awt.Color(254, 182, 53));
        bSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSubmitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bSubmitMouseExited(evt);
            }
        });

        arrRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/arrowright.png"))); // NOI18N

        javax.swing.GroupLayout bSubmitLayout = new javax.swing.GroupLayout(bSubmit);
        bSubmit.setLayout(bSubmitLayout);
        bSubmitLayout.setHorizontalGroup(
            bSubmitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bSubmitLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(arrRight)
                .addGap(23, 23, 23))
        );
        bSubmitLayout.setVerticalGroup(
            bSubmitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bSubmitLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(arrRight)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pLoginL.add(bSubmit);
        bSubmit.setBounds(520, 300, 70, 160);

        judul.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        judul.setText("Genre");
        pLoginL.add(judul);
        judul.setBounds(50, 320, 120, 29);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel1.setText("Add Album");
        pLoginL.add(jLabel1);
        jLabel1.setBounds(200, 50, 240, 50);

        jPanel5.setBackground(new java.awt.Color(249, 249, 249));

        addJudulS2.setBackground(new java.awt.Color(249, 249, 249));
        addJudulS2.setBorder(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addJudulS2, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addJudulS2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pLoginL.add(jPanel5);
        jPanel5.setBounds(40, 250, 440, 60);

        jPanel4.setBackground(new java.awt.Color(249, 249, 249));

        tfGenre.setBackground(new java.awt.Color(249, 249, 249));
        tfGenre.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        tfGenre.setBorder(null);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfGenre, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfGenre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pLoginL.add(jPanel4);
        jPanel4.setBounds(40, 350, 440, 60);

        judul2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        judul2.setText("Name");
        pLoginL.add(judul2);
        judul2.setBounds(50, 220, 120, 29);

        judul3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        judul3.setText("Released Date");
        pLoginL.add(judul3);
        judul3.setBounds(50, 410, 160, 29);

        jPanel6.setBackground(new java.awt.Color(249, 249, 249));

        tfRilis.setBackground(new java.awt.Color(249, 249, 249));
        tfRilis.setBorder(null);
        tfRilis.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/M/yyyy"))));
        tfRilis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRilisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfRilis, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfRilis, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pLoginL.add(jPanel6);
        jPanel6.setBounds(40, 440, 440, 60);

        judul4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        judul4.setText("Produced by");
        pLoginL.add(judul4);
        judul4.setBounds(50, 510, 150, 29);

        jPanel7.setBackground(new java.awt.Color(249, 249, 249));

        tfProduser.setBackground(new java.awt.Color(249, 249, 249));
        tfProduser.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        tfProduser.setBorder(null);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfProduser, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfProduser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pLoginL.add(jPanel7);
        jPanel7.setBounds(40, 540, 440, 60);

        tblArtist.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        tblArtist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblArtist);

        bPenyanyi.setBackground(new java.awt.Color(254, 182, 53));
        bPenyanyi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("Pilih Penyanyi");

        javax.swing.GroupLayout bPenyanyiLayout = new javax.swing.GroupLayout(bPenyanyi);
        bPenyanyi.setLayout(bPenyanyiLayout);
        bPenyanyiLayout.setHorizontalGroup(
            bPenyanyiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bPenyanyiLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        bPenyanyiLayout.setVerticalGroup(
            bPenyanyiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bPenyanyiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bPenyanyi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(bPenyanyi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pLoginL, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLoginL, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSubmitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bSubmitMouseClicked

    private void bSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSubmitMouseEntered
        bSubmit.setBackground(new Color(255, 197, 91));
    }//GEN-LAST:event_bSubmitMouseEntered

    private void bSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSubmitMouseExited
        bSubmit.setBackground(new Color(254, 182, 53));
    }//GEN-LAST:event_bSubmitMouseExited

    private void tfRilisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRilisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRilisActionPerformed
    public String getTfName() {
        return tfName.getText();
    }

    public String getTfGenre() {
        return tfGenre.getText();
    }
    public JTable gettblArtist() {
        return tblArtist;
    }
    public void setbPenyanyi(MouseAdapter act){
        bPenyanyi.addMouseListener(act);
    }
    public String getTfIDAlbum() {
        return tfIDAlbum.getText();
    }
    public String getTfProduser() {
        return tfProduser.getText();
    }

    public Date getTfRilis() {
        int year,month,day;
        String[] sparate = tfRilis.getText().split("/");
        year = Integer.valueOf(sparate[2]);
        month = Integer.valueOf(sparate[1]);
        day = Integer.valueOf(sparate[0]);
        return tools.Tools.insertDate(year, month, day);
    }
    public void addBSubmitAdapter(MouseAdapter adapter) {
        bSubmit.addMouseListener(adapter);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addJudulS2;
    private javax.swing.JLabel arrRight;
    private javax.swing.JPanel bPenyanyi;
    private javax.swing.JPanel bSubmit;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    private javax.swing.JLabel judul4;
    private javax.swing.JPanel pLoginL;
    private javax.swing.JTable tblArtist;
    private javax.swing.JTextField tfGenre;
    private javax.swing.JTextField tfIDAlbum;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfProduser;
    private javax.swing.JFormattedTextField tfRilis;
    // End of variables declaration//GEN-END:variables
}
