/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author ciara
 */
public class createManusia extends javax.swing.JFrame {

    /**
     * Creates new form createManusia
     */
    public createManusia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pDashboard = new javax.swing.JPanel();
        createC = new javax.swing.JLabel();
        HomeC = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bLoginC = new javax.swing.JLabel();
        iconSilau = new javax.swing.JLabel();
        pOrgsC = new javax.swing.JPanel();
        pSignupC = new javax.swing.JPanel();
        tfNIK = new javax.swing.JTextField();
        bNext = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        tfNohp = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfBirthday = new javax.swing.JFormattedTextField();
        bDaftarC = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1921, 1100));

        jPanel1.setBackground(new java.awt.Color(249, 117, 117));
        jPanel1.setPreferredSize(new java.awt.Dimension(1921, 1100));
        jPanel1.setLayout(null);

        pDashboard.setBackground(new java.awt.Color(22, 56, 80));

        createC.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        createC.setForeground(new java.awt.Color(255, 255, 255));
        createC.setText("Create an Account");

        HomeC.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        HomeC.setForeground(new java.awt.Color(255, 255, 255));
        HomeC.setText("Home");

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\pictures\\CorelDraw\\lirik\\button\\separator.png")); // NOI18N

        bLoginC.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bLoginC.setForeground(new java.awt.Color(255, 255, 255));
        bLoginC.setText("Login");

        iconSilau.setIcon(new javax.swing.ImageIcon("D:\\pictures\\CorelDraw\\lirik\\button\\icon.png")); // NOI18N

        javax.swing.GroupLayout pDashboardLayout = new javax.swing.GroupLayout(pDashboard);
        pDashboard.setLayout(pDashboardLayout);
        pDashboardLayout.setHorizontalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashboardLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(iconSilau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1026, Short.MAX_VALUE)
                .addComponent(HomeC)
                .addGap(83, 83, 83)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(createC)
                .addGap(100, 100, 100)
                .addComponent(bLoginC)
                .addGap(108, 108, 108))
        );
        pDashboardLayout.setVerticalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashboardLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(bLoginC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                        .addComponent(createC)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                        .addComponent(iconSilau)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                        .addComponent(HomeC)
                        .addGap(41, 41, 41))))
        );

        jPanel1.add(pDashboard);
        pDashboard.setBounds(0, 0, 1920, 120);

        pOrgsC.setBackground(new java.awt.Color(254, 182, 53));
        pOrgsC.setLayout(null);

        pSignupC.setBackground(new java.awt.Color(255, 255, 255));
        pSignupC.setLayout(null);

        tfNIK.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        tfNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNIKActionPerformed(evt);
            }
        });
        pSignupC.add(tfNIK);
        tfNIK.setBounds(80, 160, 440, 60);

        bNext.setBackground(new java.awt.Color(254, 182, 63));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel11.setText("NEXT");

        javax.swing.GroupLayout bNextLayout = new javax.swing.GroupLayout(bNext);
        bNext.setLayout(bNextLayout);
        bNextLayout.setHorizontalGroup(
            bNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bNextLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel11)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        bNextLayout.setVerticalGroup(
            bNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bNextLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        pSignupC.add(bNext);
        bNext.setBounds(80, 550, 440, 60);

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel9.setText("NIK");
        pSignupC.add(jLabel9);
        jLabel9.setBounds(80, 130, 180, 29);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Full Name");
        pSignupC.add(jLabel12);
        jLabel12.setBounds(80, 30, 180, 29);

        tfNama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });
        pSignupC.add(tfNama);
        tfNama.setBounds(80, 60, 440, 60);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Mobile Number");
        pSignupC.add(jLabel13);
        jLabel13.setBounds(80, 230, 180, 29);

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        pSignupC.add(jLabel14);
        jLabel14.setBounds(80, 430, 180, 0);

        tfAddress.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        tfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddressActionPerformed(evt);
            }
        });
        pSignupC.add(tfAddress);
        tfAddress.setBounds(80, 360, 440, 60);

        tfNohp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        tfNohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNohpActionPerformed(evt);
            }
        });
        pSignupC.add(tfNohp);
        tfNohp.setBounds(80, 260, 440, 60);

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel15.setText("Birthday (dd/mm/yyyy)");
        pSignupC.add(jLabel15);
        jLabel15.setBounds(80, 430, 260, 29);

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel16.setText("Address");
        pSignupC.add(jLabel16);
        jLabel16.setBounds(80, 330, 180, 29);

        tfBirthday.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yyyy"))));
        tfBirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBirthdayActionPerformed(evt);
            }
        });
        pSignupC.add(tfBirthday);
        tfBirthday.setBounds(80, 460, 440, 60);

        pOrgsC.add(pSignupC);
        pSignupC.setBounds(660, 80, 610, 650);

        bDaftarC.setIcon(new javax.swing.ImageIcon("D:\\pictures\\CorelDraw\\lirik\\button\\daftarkan dirimu.png")); // NOI18N
        pOrgsC.add(bDaftarC);
        bDaftarC.setBounds(832, 704, 250, 112);

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 120)); // NOI18N
        jLabel5.setText("Temukan Lirik Lagu");
        pOrgsC.add(jLabel5);
        jLabel5.setBounds(420, 210, 1114, 142);

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 120)); // NOI18N
        jLabel6.setText("Favoritmu.");
        pOrgsC.add(jLabel6);
        jLabel6.setBounds(910, 380, 622, 161);

        jPanel1.add(pOrgsC);
        pOrgsC.setBounds(0, 120, 1920, 980);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNIKActionPerformed
        
    }//GEN-LAST:event_tfNIKActionPerformed

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void tfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddressActionPerformed

    private void tfNohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNohpActionPerformed

    private void tfBirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBirthdayActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HomeC;
    private javax.swing.JLabel bDaftarC;
    private javax.swing.JLabel bLoginC;
    private javax.swing.JPanel bNext;
    private javax.swing.JLabel createC;
    private javax.swing.JLabel iconSilau;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pDashboard;
    private javax.swing.JPanel pOrgsC;
    private javax.swing.JPanel pSignupC;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JFormattedTextField tfBirthday;
    private javax.swing.JTextField tfNIK;
    private javax.swing.JTextField tfNama;
    private javax.swing.JFormattedTextField tfNohp;
    // End of variables declaration//GEN-END:variables
}
