/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author ciara
 */
public class dialogLogin extends javax.swing.JFrame {
    private static dialogLogin obj=null;
    /**
     * Creates new form dialogLogin
     */
    public dialogLogin() {
        initComponents();
    }
    public static dialogLogin getObj(){
        if(obj==null){
           obj= new dialogLogin();
        }return obj;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLoginL = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tfUsername = new javax.swing.JTextField();
        usernameL = new javax.swing.JLabel();
        passL = new javax.swing.JLabel();
        logAdminL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tfPass = new javax.swing.JPasswordField();
        showPass = new javax.swing.JLabel();
        bLogUserL = new javax.swing.JPanel();
        arrRight = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(620, 370));
        setResizable(false);

        pLoginL.setBackground(new java.awt.Color(255, 255, 255));
        pLoginL.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(249, 249, 249));

        tfUsername.setBackground(new java.awt.Color(249, 249, 249));
        tfUsername.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        tfUsername.setBorder(null);
        tfUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUsernameFocusLost(evt);
            }
        });
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pLoginL.add(jPanel2);
        jPanel2.setBounds(40, 140, 440, 60);

        usernameL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        usernameL.setText("Username");
        pLoginL.add(usernameL);
        usernameL.setBounds(50, 100, 130, 29);

        passL.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        passL.setText("Password");
        pLoginL.add(passL);
        passL.setBounds(50, 200, 200, 29);

        logAdminL.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        logAdminL.setForeground(new java.awt.Color(254, 182, 53));
        logAdminL.setText("Login as Admin");
        logAdminL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logAdminL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logAdminLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logAdminLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logAdminLMouseExited(evt);
            }
        });
        pLoginL.add(logAdminL);
        logAdminL.setBounds(40, 300, 200, 29);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\pictures\\CorelDraw\\lirik\\button\\login icon.png")); // NOI18N
        pLoginL.add(jLabel3);
        jLabel3.setBounds(120, 20, 365, 70);

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));

        tfPass.setBackground(new java.awt.Color(249, 249, 249));
        tfPass.setFont(tfPass.getFont().deriveFont((float)24));
        tfPass.setBorder(null);
        tfPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPassFocusLost(evt);
            }
        });
        tfPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfPassMouseClicked(evt);
            }
        });
        tfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassActionPerformed(evt);
            }
        });
        tfPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPassKeyPressed(evt);
            }
        });

        showPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/seenMini.png"))); // NOI18N
        showPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showPassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPass)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pLoginL.add(jPanel1);
        jPanel1.setBounds(40, 230, 440, 60);

        bLogUserL.setBackground(new java.awt.Color(254, 182, 53));
        bLogUserL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bLogUserL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLogUserLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bLogUserLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bLogUserLMouseExited(evt);
            }
        });

        arrRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/arrowright.png"))); // NOI18N

        javax.swing.GroupLayout bLogUserLLayout = new javax.swing.GroupLayout(bLogUserL);
        bLogUserL.setLayout(bLogUserLLayout);
        bLogUserLLayout.setHorizontalGroup(
            bLogUserLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bLogUserLLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(arrRight)
                .addGap(23, 23, 23))
        );
        bLogUserLLayout.setVerticalGroup(
            bLogUserLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bLogUserLLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(arrRight)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pLoginL.add(bLogUserL);
        bLogUserL.setBounds(500, 130, 70, 160);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pLoginL, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pLoginL, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void logAdminLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logAdminLMouseEntered
        logAdminL.setForeground(new Color(255, 197, 91));
    }//GEN-LAST:event_logAdminLMouseEntered

    private void logAdminLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logAdminLMouseExited
        logAdminL.setForeground(new Color(254, 182, 53));
    }//GEN-LAST:event_logAdminLMouseExited

    private void bLogUserLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogUserLMouseClicked
        //JOptionPane.showMessageDialog(rootPane, "Berhasil Login");
        //dialogLogin.getObj().dispose();
        //viewHomepage.getObj().setVisible(false);
        //searchUser.getObj().setVisible(true);
    }//GEN-LAST:event_bLogUserLMouseClicked

    private void bLogUserLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogUserLMouseEntered
        bLogUserL.setBackground(new Color(255, 197, 91));
    }//GEN-LAST:event_bLogUserLMouseEntered

    private void bLogUserLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogUserLMouseExited
        bLogUserL.setBackground(new Color(254, 182, 53));
    }//GEN-LAST:event_bLogUserLMouseExited
    public  int i=0;
    private void showPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPassMouseClicked
        // TODO add your handling code here:
        
        if (i%2 == 0 ){
            tfPass.setEchoChar((char)0);
            i++;
        }else{
           tfPass.setEchoChar('•');
           i++;
        }
        System.out.println(i);
    }//GEN-LAST:event_showPassMouseClicked

    private void tfUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusLost
        // TODO add your handling code here:
        if(tfUsername.getText().equals("")){
            tfUsername.setText(" Username");
            tfUsername.setForeground(new Color(180,180,180));
        }
    }//GEN-LAST:event_tfUsernameFocusLost

    private void tfUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusGained
        // TODO add your handling code here:
        if(tfUsername.getText().trim().equals("Username")){
            tfUsername.setText("");
            tfUsername.setForeground(Color.black);
        }
    }//GEN-LAST:event_tfUsernameFocusGained

    private void tfPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPassKeyPressed
        // UBAH! BUAT ABIS ISI PASSWORD
    }//GEN-LAST:event_tfPassKeyPressed

    private void tfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPassActionPerformed

    private void tfPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPassMouseClicked
        tfPass.setEchoChar('•');
    }//GEN-LAST:event_tfPassMouseClicked

    private void tfPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPassFocusLost
        
    }//GEN-LAST:event_tfPassFocusLost

    private void tfPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPassFocusGained
     
    }//GEN-LAST:event_tfPassFocusGained

    private void logAdminLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logAdminLMouseClicked
        //JOptionPane.showMessageDialog(rootPane, "Berhasil Login");
        
    }//GEN-LAST:event_logAdminLMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrRight;
    private javax.swing.JPanel bLogUserL;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logAdminL;
    private javax.swing.JPanel pLoginL;
    private javax.swing.JLabel passL;
    private javax.swing.JLabel showPass;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JLabel usernameL;
    // End of variables declaration//GEN-END:variables

    void close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public String getLoginUsername() {
        return tfUsername.getText();
    }
    public String getTfUSername() {
        return tfUsername.getText();
    }
    
    public String getTfPass() {
        return tfPass.getText();
    }
    
    
    public void addbLogUserLAdapter(MouseAdapter m){
        bLogUserL.addMouseListener(m);
    }

    public void addlogAdminLAdapter(MouseAdapter mouseAdapter) {
        logAdminL.addMouseListener(mouseAdapter); //To change body of generated methods, choose Tools | Templates.
    }
}
