/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentListener;

/**
 *
 * @author ciara
 */
public class searchUser extends javax.swing.JFrame {
private static searchUser obj=null;
    /**
     * Creates new form searchUser
     */
    public searchUser() {
        initComponents();
    }
    public static searchUser getObj(){
        if(obj==null){
           obj= new searchUser();
        }return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pDashboard = new javax.swing.JPanel();
        iconSilau = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        lNama = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Search = new javax.swing.JLabel();
        tracklist = new javax.swing.JLabel();
        bSignout = new javax.swing.JLabel();
        bEditP = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        temukan = new javax.swing.JLabel();
        fav = new javax.swing.JLabel();
        panelSearch = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        searchIcon = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1351, 721));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(249, 117, 117));
        jPanel1.setPreferredSize(new java.awt.Dimension(1921, 1100));
        jPanel1.setLayout(null);

        pDashboard.setBackground(new java.awt.Color(22, 56, 80));

        iconSilau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icon.png"))); // NOI18N

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/user.png"))); // NOI18N

        lNama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lNama.setForeground(new java.awt.Color(255, 255, 255));
        lNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNama.setText("12345678901234567890");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        Search.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("Search");

        tracklist.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        tracklist.setForeground(new java.awt.Color(255, 255, 255));
        tracklist.setText("Tracklist");
        tracklist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tracklist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tracklistMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tracklistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tracklistMouseExited(evt);
            }
        });

        bSignout.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bSignout.setForeground(new java.awt.Color(255, 255, 255));
        bSignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/signoutIcon.png"))); // NOI18N
        bSignout.setText("Sign Out");
        bSignout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSignout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSignoutMouseClicked(evt);
            }
        });

        bEditP.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        bEditP.setForeground(new java.awt.Color(255, 255, 255));
        bEditP.setText("Edit");
        bEditP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEditP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEditPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pDashboardLayout = new javax.swing.GroupLayout(pDashboard);
        pDashboard.setLayout(pDashboardLayout);
        pDashboardLayout.setHorizontalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashboardLayout.createSequentialGroup()
                .addGap(0, 56, Short.MAX_VALUE)
                .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                        .addComponent(iconSilau)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                        .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDashboardLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(userIcon))
                            .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bEditP)
                            .addGroup(pDashboardLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bSignout)
                                    .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tracklist)
                                        .addComponent(Search)))))
                        .addGap(54, 54, 54))))
        );
        pDashboardLayout.setVerticalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashboardLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(iconSilau)
                .addGap(45, 45, 45)
                .addComponent(userIcon)
                .addGap(18, 18, 18)
                .addComponent(lNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(bEditP)
                .addGap(16, 16, 16)
                .addComponent(Search)
                .addGap(18, 18, 18)
                .addComponent(tracklist)
                .addGap(248, 248, 248)
                .addComponent(bSignout)
                .addContainerGap(425, Short.MAX_VALUE))
        );

        jPanel1.add(pDashboard);
        pDashboard.setBounds(0, 0, 370, 1100);

        jPanel2.setBackground(new java.awt.Color(254, 182, 53));
        jPanel2.setLayout(null);

        temukan.setFont(new java.awt.Font("Roboto Black", 0, 70)); // NOI18N
        temukan.setText("Temukan lirik lagu");
        jPanel2.add(temukan);
        temukan.setBounds(90, 240, 620, 142);

        fav.setFont(new java.awt.Font("Roboto Black", 0, 70)); // NOI18N
        fav.setText("favoritmu.");
        jPanel2.add(fav);
        fav.setBounds(100, 340, 622, 161);

        panelSearch.setBackground(new java.awt.Color(255, 255, 255));

        search.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        search.setBorder(null);
        search.setMargin(new java.awt.Insets(2, 4, 2, 2));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });

        searchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/search.png"))); // NOI18N

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(searchIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSearchLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(searchIcon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelSearch);
        panelSearch.setBounds(80, 120, 850, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(370, 0, 980, 1070);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1351, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void tracklistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tracklistMouseClicked
        searchUser.getObj().dispose();
        trackUser.getObj().setVisible(true);
    }//GEN-LAST:event_tracklistMouseClicked

    private void bSignoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSignoutMouseClicked
        searchUser.getObj().dispose();
    }//GEN-LAST:event_bSignoutMouseClicked

    private void tracklistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tracklistMouseEntered
        tracklist.setBackground(new Color(255, 197, 91));
    }//GEN-LAST:event_tracklistMouseEntered
     
    private void tracklistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tracklistMouseExited
        tracklist.setBackground(new Color(254, 182, 53));   // TODO add your handling code here:
    }//GEN-LAST:event_tracklistMouseExited

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        
//        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
//            searchUser.getObj().dispose();
//            searchUserResult.getObj().setVisible(true);
//        }
    }//GEN-LAST:event_searchKeyPressed

    private void bEditPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditPMouseClicked
        updateProfile.getObj().setVisible(true);
    }//GEN-LAST:event_bEditPMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Search;
    private javax.swing.JLabel bEditP;
    private javax.swing.JLabel bSignout;
    private javax.swing.JLabel fav;
    private javax.swing.JLabel iconSilau;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lNama;
    private javax.swing.JPanel pDashboard;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JTextField search;
    private javax.swing.JLabel searchIcon;
    private javax.swing.JLabel temukan;
    private javax.swing.JLabel tracklist;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables

    public void settfSearchListener(DocumentListener listener){
        search.getDocument().addDocumentListener(listener);
    }

    public void addSearchListener(KeyListener e){
        search.addKeyListener(e);
    }
        
    public String getSearch() {
        return search.getText();
    }
    
}
