/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import javax.swing.JLabel;

/**
 *
 * @author ciara
 */
public class searchUserResult extends javax.swing.JFrame {
private static searchUserResult obj=null;
    /**
     * Creates new form searchUser
     */
   
    public searchUserResult() {
        initComponents();
    }
    public static searchUserResult getObj(){
        if(obj==null){
           obj= new searchUserResult();
        }return obj;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pDashboard = new javax.swing.JPanel();
        iconSilau = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        lNama = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Search = new javax.swing.JLabel();
        tracklist = new javax.swing.JLabel();
        bSignout = new javax.swing.JLabel();
        bEditP = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelSearch = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        searchIcon = new javax.swing.JLabel();
        lDicari = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pArtist1 = new javax.swing.JPanel();
        ArtistIcon1 = new javax.swing.JLabel();
        lArtist1 = new javax.swing.JLabel();
        pSong2 = new javax.swing.JPanel();
        lSong2 = new javax.swing.JLabel();
        SongIcon2 = new javax.swing.JLabel();
        bsongaddT2 = new javax.swing.JLabel();
        seenS2 = new javax.swing.JLabel();
        pArtist2 = new javax.swing.JPanel();
        ArtistIcon2 = new javax.swing.JLabel();
        lArtist2 = new javax.swing.JLabel();
        pSong1 = new javax.swing.JPanel();
        SongIcon1 = new javax.swing.JLabel();
        lSong1 = new javax.swing.JLabel();
        bSongaddT1 = new javax.swing.JLabel();
        seenS1 = new javax.swing.JLabel();
        pWord2 = new javax.swing.JPanel();
        WordIcon2 = new javax.swing.JLabel();
        lWord2 = new javax.swing.JLabel();
        lWordart3 = new javax.swing.JLabel();
        bWadd2 = new javax.swing.JLabel();
        seenW2 = new javax.swing.JLabel();
        pWord1 = new javax.swing.JPanel();
        WordIcon1 = new javax.swing.JLabel();
        lWord1 = new javax.swing.JLabel();
        lWordart4 = new javax.swing.JLabel();
        bWadd1 = new javax.swing.JLabel();
        seenW1 = new javax.swing.JLabel();
        bSmoreWord = new javax.swing.JLabel();
        bSmoreSong = new javax.swing.JLabel();
        bSmoreArt = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1344, 726));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(249, 117, 117));
        jPanel1.setPreferredSize(new java.awt.Dimension(1921, 1100));
        jPanel1.setLayout(null);

        pDashboard.setBackground(new java.awt.Color(22, 56, 80));

        iconSilau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icon.png"))); // NOI18N

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/user.png"))); // NOI18N

        lNama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lNama.setForeground(new java.awt.Color(255, 255, 255));
        lNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNama.setText("12345678901234567890");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        Search.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("Search");
        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tracklist.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        tracklist.setForeground(new java.awt.Color(255, 255, 255));
        tracklist.setText("Tracklist");
        tracklist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tracklist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tracklistMouseClicked(evt);
            }
        });

        bSignout.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bSignout.setForeground(new java.awt.Color(255, 255, 255));
        bSignout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/signoutIcon.png"))); // NOI18N
        bSignout.setText("Sign Out");
        bSignout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSignout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSignoutMouseClicked(evt);
            }
        });

        bEditP.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        bEditP.setForeground(new java.awt.Color(255, 255, 255));
        bEditP.setText("Edit");
        bEditP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEditP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEditPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pDashboardLayout = new javax.swing.GroupLayout(pDashboard);
        pDashboard.setLayout(pDashboardLayout);
        pDashboardLayout.setHorizontalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashboardLayout.createSequentialGroup()
                .addGap(0, 56, Short.MAX_VALUE)
                .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                        .addComponent(iconSilau)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                        .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDashboardLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(userIcon))
                            .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bEditP)
                            .addGroup(pDashboardLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bSignout)
                                    .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tracklist)
                                        .addComponent(Search)))))
                        .addGap(54, 54, 54))))
        );
        pDashboardLayout.setVerticalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashboardLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(iconSilau)
                .addGap(45, 45, 45)
                .addComponent(userIcon)
                .addGap(18, 18, 18)
                .addComponent(lNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bEditP)
                .addGap(8, 8, 8)
                .addComponent(Search)
                .addGap(18, 18, 18)
                .addComponent(tracklist)
                .addGap(252, 252, 252)
                .addComponent(bSignout)
                .addContainerGap(421, Short.MAX_VALUE))
        );

        jPanel1.add(pDashboard);
        pDashboard.setBounds(0, 0, 370, 1100);

        jPanel2.setBackground(new java.awt.Color(254, 182, 53));
        jPanel2.setLayout(null);

        panelSearch.setBackground(new java.awt.Color(255, 255, 255));

        search.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        search.setBorder(null);
        search.setMargin(new java.awt.Insets(2, 4, 2, 2));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });

        searchIcon.setIcon(new javax.swing.ImageIcon("D:\\pictures\\CorelDraw\\lirik\\button\\search.png")); // NOI18N

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(searchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchIcon)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel2.add(panelSearch);
        panelSearch.setBounds(90, 60, 770, 50);

        lDicari.setFont(new java.awt.Font("Roboto", 2, 36)); // NOI18N
        lDicari.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDicari.setText("yg dicari");
        jPanel2.add(lDicari);
        lDicari.setBounds(370, 0, 200, 60);

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 27)); // NOI18N
        jLabel3.setText("Songs");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 110, 110, 40);

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 27)); // NOI18N
        jLabel4.setText("Artist");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(90, 300, 80, 40);

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 27)); // NOI18N
        jLabel5.setText("Words Matches");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 480, 200, 50);

        pArtist1.setBackground(new java.awt.Color(254, 218, 153));
        pArtist1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pArtist1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pArtist1MouseClicked(evt);
            }
        });

        ArtistIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/singer.png"))); // NOI18N
        ArtistIcon1.setText("jLabel7");

        lArtist1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lArtist1.setText("Artist");

        javax.swing.GroupLayout pArtist1Layout = new javax.swing.GroupLayout(pArtist1);
        pArtist1.setLayout(pArtist1Layout);
        pArtist1Layout.setHorizontalGroup(
            pArtist1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pArtist1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ArtistIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lArtist1)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        pArtist1Layout.setVerticalGroup(
            pArtist1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pArtist1Layout.createSequentialGroup()
                .addGroup(pArtist1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pArtist1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ArtistIcon1))
                    .addGroup(pArtist1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lArtist1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(pArtist1);
        pArtist1.setBounds(90, 340, 340, 140);

        pSong2.setBackground(new java.awt.Color(254, 218, 153));

        lSong2.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lSong2.setText("Judul Lagu");
        lSong2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lSong2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lSong2MouseClicked(evt);
            }
        });

        SongIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/albumm.png"))); // NOI18N
        SongIcon2.setText("jLabel7");

        bsongaddT2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        bsongaddT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/addTrack.png"))); // NOI18N
        bsongaddT2.setText("Add to Tracklist");
        bsongaddT2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsongaddT2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsongaddT2MouseClicked(evt);
            }
        });

        seenS2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        seenS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/seenMini.png"))); // NOI18N
        seenS2.setText("seen");

        javax.swing.GroupLayout pSong2Layout = new javax.swing.GroupLayout(pSong2);
        pSong2.setLayout(pSong2Layout);
        pSong2Layout.setHorizontalGroup(
            pSong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSong2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SongIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pSong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bsongaddT2)
                    .addGroup(pSong2Layout.createSequentialGroup()
                        .addComponent(lSong2)
                        .addGap(26, 26, 26)
                        .addComponent(seenS2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pSong2Layout.setVerticalGroup(
            pSong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSong2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pSong2Layout.createSequentialGroup()
                        .addGroup(pSong2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lSong2)
                            .addComponent(seenS2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bsongaddT2))
                    .addComponent(SongIcon2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(pSong2);
        pSong2.setBounds(90, 150, 340, 140);

        pArtist2.setBackground(new java.awt.Color(254, 218, 153));
        pArtist2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pArtist2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pArtist2MouseClicked(evt);
            }
        });

        ArtistIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/singer.png"))); // NOI18N

        lArtist2.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lArtist2.setText("Artist");

        javax.swing.GroupLayout pArtist2Layout = new javax.swing.GroupLayout(pArtist2);
        pArtist2.setLayout(pArtist2Layout);
        pArtist2Layout.setHorizontalGroup(
            pArtist2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pArtist2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ArtistIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lArtist2)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        pArtist2Layout.setVerticalGroup(
            pArtist2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pArtist2Layout.createSequentialGroup()
                .addGroup(pArtist2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pArtist2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ArtistIcon2))
                    .addGroup(pArtist2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lArtist2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(pArtist2);
        pArtist2.setBounds(460, 340, 350, 140);

        pSong1.setBackground(new java.awt.Color(254, 218, 153));

        SongIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/albumm.png"))); // NOI18N
        SongIcon1.setText("jLabel7");

        lSong1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lSong1.setText("Judul Lagu");
        lSong1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lSong1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lSong1MouseClicked(evt);
            }
        });

        bSongaddT1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        bSongaddT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/addTrack.png"))); // NOI18N
        bSongaddT1.setText("Add to Tracklist");
        bSongaddT1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        seenS1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        seenS1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/seenMini.png"))); // NOI18N
        seenS1.setText("seen");

        javax.swing.GroupLayout pSong1Layout = new javax.swing.GroupLayout(pSong1);
        pSong1.setLayout(pSong1Layout);
        pSong1Layout.setHorizontalGroup(
            pSong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSong1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SongIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pSong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSongaddT1)
                    .addGroup(pSong1Layout.createSequentialGroup()
                        .addComponent(lSong1)
                        .addGap(30, 30, 30)
                        .addComponent(seenS1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pSong1Layout.setVerticalGroup(
            pSong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSong1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pSong1Layout.createSequentialGroup()
                        .addGroup(pSong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lSong1)
                            .addComponent(seenS1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bSongaddT1))
                    .addComponent(SongIcon1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(pSong1);
        pSong1.setBounds(460, 150, 350, 140);

        pWord2.setBackground(new java.awt.Color(254, 218, 153));

        WordIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/word.png"))); // NOI18N
        WordIcon2.setText("jLabel7");

        lWord2.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lWord2.setText("Judul Lagu");
        lWord2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lWord2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lWord2MouseClicked(evt);
            }
        });

        lWordart3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lWordart3.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ullamcorper mauris eget massa venenatis,");

        bWadd2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        bWadd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/addTrack.png"))); // NOI18N
        bWadd2.setText("Add to Tracklist");
        bWadd2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        seenW2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        seenW2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/seenMini.png"))); // NOI18N
        seenW2.setText("seen");

        javax.swing.GroupLayout pWord2Layout = new javax.swing.GroupLayout(pWord2);
        pWord2.setLayout(pWord2Layout);
        pWord2Layout.setHorizontalGroup(
            pWord2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pWord2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WordIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pWord2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bWadd2)
                    .addGroup(pWord2Layout.createSequentialGroup()
                        .addComponent(lWord2)
                        .addGap(32, 32, 32)
                        .addComponent(seenW2))
                    .addComponent(lWordart3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pWord2Layout.setVerticalGroup(
            pWord2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pWord2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pWord2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pWord2Layout.createSequentialGroup()
                        .addGroup(pWord2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lWord2)
                            .addComponent(seenW2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lWordart3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bWadd2))
                    .addComponent(WordIcon2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(pWord2);
        pWord2.setBounds(460, 520, 350, 140);

        pWord1.setBackground(new java.awt.Color(254, 218, 153));

        WordIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/word.png"))); // NOI18N
        WordIcon1.setText("jLabel7");

        lWord1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        lWord1.setText("Judul Lagu");
        lWord1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lWord1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lWord1MouseClicked(evt);
            }
        });

        lWordart4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lWordart4.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ullamcorper mauris eget massa venenatis,");

        bWadd1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        bWadd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/addTrack.png"))); // NOI18N
        bWadd1.setText("Add to Tracklist");
        bWadd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        seenW1.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        seenW1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/seenMini.png"))); // NOI18N
        seenW1.setText("seen");

        javax.swing.GroupLayout pWord1Layout = new javax.swing.GroupLayout(pWord1);
        pWord1.setLayout(pWord1Layout);
        pWord1Layout.setHorizontalGroup(
            pWord1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pWord1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WordIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pWord1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bWadd1)
                    .addGroup(pWord1Layout.createSequentialGroup()
                        .addComponent(lWord1)
                        .addGap(18, 18, 18)
                        .addComponent(seenW1))
                    .addComponent(lWordart4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pWord1Layout.setVerticalGroup(
            pWord1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pWord1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pWord1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pWord1Layout.createSequentialGroup()
                        .addGroup(pWord1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lWord1)
                            .addComponent(seenW1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lWordart4)
                        .addGap(18, 18, 18)
                        .addComponent(bWadd1))
                    .addComponent(WordIcon1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(pWord1);
        pWord1.setBounds(90, 520, 340, 140);

        bSmoreWord.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        bSmoreWord.setText("see more >");
        bSmoreWord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSmoreWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSmoreWordMouseClicked(evt);
            }
        });
        jPanel2.add(bSmoreWord);
        bSmoreWord.setBounds(300, 490, 110, 30);

        bSmoreSong.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        bSmoreSong.setText("see more >");
        bSmoreSong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSmoreSong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSmoreSongMouseClicked(evt);
            }
        });
        jPanel2.add(bSmoreSong);
        bSmoreSong.setBounds(190, 120, 110, 20);

        bSmoreArt.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        bSmoreArt.setText("see more >");
        bSmoreArt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSmoreArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSmoreArtMouseClicked(evt);
            }
        });
        jPanel2.add(bSmoreArt);
        bSmoreArt.setBounds(190, 310, 110, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(370, 0, 980, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1344, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            searchUser.getObj().dispose();
            searchUserResult.getObj().dispose();
            searchUserResult.getObj().setVisible(true);
        }
    }//GEN-LAST:event_searchKeyPressed

    private void bsongaddT2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsongaddT2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bsongaddT2MouseClicked

    private void tracklistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tracklistMouseClicked
        //searchUserResult.getObj().dispose();
        trackUser.getObj().setVisible(true);
    }//GEN-LAST:event_tracklistMouseClicked

    private void bSignoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSignoutMouseClicked
        searchUserResult.getObj().dispose();
    }//GEN-LAST:event_bSignoutMouseClicked

    private void bSmoreSongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSmoreSongMouseClicked
        //searchUserResult.getObj().dispose();
        //smSong.getObj().setVisible(true);
    }//GEN-LAST:event_bSmoreSongMouseClicked

    private void bSmoreArtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSmoreArtMouseClicked
        //searchUserResult.getObj().dispose();
        //smArtist.getObj().setVisible(true);
    }//GEN-LAST:event_bSmoreArtMouseClicked

    private void bSmoreWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSmoreWordMouseClicked
        //searchUserResult.getObj().dispose();
        //smWord.getObj().setVisible(true);
    }//GEN-LAST:event_bSmoreWordMouseClicked

    private void pArtist1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pArtist1MouseClicked
        dArtistU.getObj().setVisible(true);
    }//GEN-LAST:event_pArtist1MouseClicked

    private void pArtist2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pArtist2MouseClicked
        dArtistU.getObj().setVisible(true);
    }//GEN-LAST:event_pArtist2MouseClicked

    private void lWord1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lWord1MouseClicked
       // dSongU.getObj().setVisible(true);
    }//GEN-LAST:event_lWord1MouseClicked

    private void lWord2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lWord2MouseClicked
        //dSongU.getObj().setVisible(true);
    }//GEN-LAST:event_lWord2MouseClicked

    private void lSong1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSong1MouseClicked
       // dSongU.getObj().setVisible(true);
    }//GEN-LAST:event_lSong1MouseClicked

    private void lSong2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSong2MouseClicked
       // dSongU.getObj().setVisible(true);
    }//GEN-LAST:event_lSong2MouseClicked

    private void bEditPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditPMouseClicked
        updateProfile.getObj().setVisible(true);
    }//GEN-LAST:event_bEditPMouseClicked
    public void addSmoreSong(MouseAdapter m){
        bSmoreSong.addMouseListener(m);
    }
    public void addSmoreWord(MouseAdapter m){
        bSmoreWord.addMouseListener(m);
    }
    public void addSmoreArt(MouseAdapter m){
        bSmoreArt.addMouseListener(m);
    }
    public void addlSong2(MouseAdapter m){
        lSong2.addMouseListener(m);
    }
    public void addlSong1(MouseAdapter m){
        lSong1.addMouseListener(m);
    }
    public void addlArtist1(MouseAdapter m){
        lArtist1.addMouseListener(m);
    }
    public void addlArtist2(MouseAdapter m){
        lArtist2.addMouseListener(m);
    }
    public void addlWord1(MouseAdapter m){
        lWord1.addMouseListener(m);
    }
    public void addlWord2(MouseAdapter m){
        lWord2.addMouseListener(m);
    }
            
    public void setlArtist1(String lArtist1) {
        this.lArtist1.setText(lArtist1);
    }

    public void setlArtist2(String lArtist2) {
        this.lArtist2.setText(lArtist2);
    }

    public void setlSong1(String lSong1) {
        this.lSong1.setText(lSong1);
    }

    public void setlSong2(String lSong2) {
        this.lSong2.setText(lSong2);
    }

    public void setlWord1(String lWord1) {
        this.lWord1.setText(lWord1);
    }

    public void setlWord2(String lWord2) {
        this.lWord2.setText(lWord2);
    }
    
    

//    public void setlSongart1(String lSongart1) {
//        this.lSongart1.setText(lSongart1);
//    }
//
//    public void setlSongart2(String lSongart2) {
//        this.lSongart2.setText(lSongart2);
//    }
//
//    public void setlWordart1(String lWordart1) {
//        this.lWordart1.setText(lWordart1);
//    }
//
//    public void setlWordart2(String lWordart2) {
//        this.lWordart2.setText(lWordart2);
//    }
//    
    
    public void setlWordart3(String lWordart3) {
        this.lWordart3.setText(lWordart3);
    }

    public void setlWordart4(String lWordart4) {
        this.lWordart4.setText(lWordart4);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArtistIcon1;
    private javax.swing.JLabel ArtistIcon2;
    private javax.swing.JLabel Search;
    private javax.swing.JLabel SongIcon1;
    private javax.swing.JLabel SongIcon2;
    private javax.swing.JLabel WordIcon1;
    private javax.swing.JLabel WordIcon2;
    private javax.swing.JLabel bEditP;
    private javax.swing.JLabel bSignout;
    private javax.swing.JLabel bSmoreArt;
    private javax.swing.JLabel bSmoreSong;
    private javax.swing.JLabel bSmoreWord;
    private javax.swing.JLabel bSongaddT1;
    private javax.swing.JLabel bWadd1;
    private javax.swing.JLabel bWadd2;
    private javax.swing.JLabel bsongaddT2;
    private javax.swing.JLabel iconSilau;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lArtist1;
    private javax.swing.JLabel lArtist2;
    private javax.swing.JLabel lDicari;
    private javax.swing.JLabel lNama;
    private javax.swing.JLabel lSong1;
    private javax.swing.JLabel lSong2;
    private javax.swing.JLabel lWord1;
    private javax.swing.JLabel lWord2;
    private javax.swing.JLabel lWordart3;
    private javax.swing.JLabel lWordart4;
    private javax.swing.JPanel pArtist1;
    private javax.swing.JPanel pArtist2;
    private javax.swing.JPanel pDashboard;
    private javax.swing.JPanel pSong1;
    private javax.swing.JPanel pSong2;
    private javax.swing.JPanel pWord1;
    private javax.swing.JPanel pWord2;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JTextField search;
    private javax.swing.JLabel searchIcon;
    private javax.swing.JLabel seenS1;
    private javax.swing.JLabel seenS2;
    private javax.swing.JLabel seenW1;
    private javax.swing.JLabel seenW2;
    private javax.swing.JLabel tracklist;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
