/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;

/**
 *
 * @author ciara
 */
public class smSong extends javax.swing.JFrame {
private static smSong obj = null;
    /**
     * Creates new form Tracklist
     */
    public smSong() {
        initComponents();
    }
    public static smSong getObj(){
        if(obj==null){
           obj= new smSong();
        }return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pDashboard = new javax.swing.JPanel();
        iconSilau = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        lNama = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Search = new javax.swing.JLabel();
        tracklist = new javax.swing.JLabel();
        bSignout1 = new javax.swing.JLabel();
        bEditP = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lDicari = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1347, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(249, 117, 117));
        jPanel1.setPreferredSize(new java.awt.Dimension(1921, 1100));
        jPanel1.setLayout(null);

        pDashboard.setBackground(new java.awt.Color(22, 56, 80));

        iconSilau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icon.png"))); // NOI18N

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/user.png"))); // NOI18N

        lNama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lNama.setForeground(new java.awt.Color(255, 255, 255));
        lNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNama.setText("12345678901234567890");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        Search.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("Search");
        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SearchMousePressed(evt);
            }
        });

        tracklist.setBackground(new java.awt.Color(255, 255, 255));
        tracklist.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        tracklist.setForeground(new java.awt.Color(255, 255, 255));
        tracklist.setText("Tracklist");
        tracklist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tracklist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tracklistMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tracklistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tracklistMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tracklistMousePressed(evt);
            }
        });

        bSignout1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        bSignout1.setForeground(new java.awt.Color(255, 255, 255));
        bSignout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/signoutIcon.png"))); // NOI18N
        bSignout1.setText("Sign Out");
        bSignout1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSignout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSignout1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bSignout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bSignout1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bSignout1MousePressed(evt);
            }
        });

        bEditP.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        bEditP.setForeground(new java.awt.Color(255, 255, 255));
        bEditP.setText("Edit");
        bEditP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bEditP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEditPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pDashboardLayout = new javax.swing.GroupLayout(pDashboard);
        pDashboard.setLayout(pDashboardLayout);
        pDashboardLayout.setHorizontalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashboardLayout.createSequentialGroup()
                .addGap(0, 56, Short.MAX_VALUE)
                .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                        .addComponent(iconSilau)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDashboardLayout.createSequentialGroup()
                        .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDashboardLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(userIcon))
                            .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bEditP)
                            .addGroup(pDashboardLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bSignout1)
                                    .addGroup(pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tracklist)
                                        .addComponent(Search)))))
                        .addGap(54, 54, 54))))
        );
        pDashboardLayout.setVerticalGroup(
            pDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashboardLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(iconSilau)
                .addGap(45, 45, 45)
                .addComponent(userIcon)
                .addGap(18, 18, 18)
                .addComponent(lNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bEditP)
                .addGap(8, 8, 8)
                .addComponent(Search)
                .addGap(18, 18, 18)
                .addComponent(tracklist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addComponent(bSignout1)
                .addGap(31, 31, 31))
        );

        jPanel1.add(pDashboard);
        pDashboard.setBounds(0, 0, 370, 720);

        jPanel2.setBackground(new java.awt.Color(254, 182, 53));
        jPanel2.setLayout(null);

        lDicari.setFont(new java.awt.Font("Roboto", 2, 48)); // NOI18N
        lDicari.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lDicari.setText("yg dicari");
        jPanel2.add(lDicari);
        lDicari.setBounds(170, 30, 210, 80);

        jScrollPane1.setBorder(null);

        jPanel3.setBackground(new java.awt.Color(254, 218, 153));

        jTable1.setBackground(new java.awt.Color(254, 218, 153));
        jTable1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(254, 218, 153));
        jTable1.setSelectionBackground(new java.awt.Color(254, 218, 153));
        jTable1.setSelectionForeground(new java.awt.Color(254, 218, 153));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(847, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(734, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 170, 900, 520);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("SONG");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(220, 110, 70, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(370, 0, 980, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1347, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
        smSong.getObj().dispose();
        searchUser.getObj().setVisible(true);
    }//GEN-LAST:event_SearchMouseClicked

    private void SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseEntered
        Search.setForeground(new Color(210,210,210));
    }//GEN-LAST:event_SearchMouseEntered

    private void SearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseExited
        Search.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_SearchMouseExited

    private void SearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMousePressed
        Search.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_SearchMousePressed

    private void tracklistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tracklistMouseClicked
        smSong.getObj().dispose();
        trackUser.getObj().setVisible(true);
    }//GEN-LAST:event_tracklistMouseClicked

    private void tracklistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tracklistMouseEntered
        tracklist.setForeground(new Color(210,210,210));
    }//GEN-LAST:event_tracklistMouseEntered

    private void tracklistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tracklistMouseExited
        tracklist.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_tracklistMouseExited

    private void tracklistMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tracklistMousePressed
        tracklist.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_tracklistMousePressed

    private void bSignout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSignout1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bSignout1MouseClicked

    private void bSignout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSignout1MouseEntered
        bSignout1.setForeground(new Color(210,210,210));
    }//GEN-LAST:event_bSignout1MouseEntered

    private void bSignout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSignout1MouseExited
        bSignout1.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_bSignout1MouseExited

    private void bSignout1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSignout1MousePressed
        bSignout1.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_bSignout1MousePressed

    private void bEditPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditPMouseClicked
        updateProfile.getObj().setVisible(true);
    }//GEN-LAST:event_bEditPMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Search;
    private javax.swing.JLabel bEditP;
    private javax.swing.JLabel bSignout1;
    private javax.swing.JLabel iconSilau;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lDicari;
    private javax.swing.JLabel lNama;
    private javax.swing.JPanel pDashboard;
    private javax.swing.JLabel tracklist;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
